version: '2'

services :

  #############################################################################
  # Redis
  cache :
    image          : redis:4.0.2-alpine
    container_name : aca_dev_redis
    mem_limit      : 1g
    command        : ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports          :
      - "${REDIS_PORT}:6379"


