version: '2.1'

services :

  #############################################################################
  # Redis
  cache :
    image          : redis:4.0.2-alpine
    container_name : aca_dev_redis
    mem_limit      : 256m
    command        : ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports          :
      - "${REDIS_PORT}:6379"
    volumes        :
      - "./tmp/env/${NODE_ENV}/redisdata:/data:cached"
      - "./etc/redis/redis.conf:/usr/local/etc/redis/redis.conf"

  #############################################################################
  # MySQL
  database :
    image          : seancannon/dev_mysql
    hostname       : bw-dev-mysql
    container_name : bw_dev_mysql
    mem_limit      : 512m
    environment    :
      - "MYSQL_ROOT_PASSWORD=${CORE_DB_ROOT_PASSWORD}"
      - "TZ=${CORE_DB_TIMEZONE}"
    volumes        :
      - "${MYSQL_VOLUME_MOUNT}"
    tmpfs          :
      - "${MYSQL_TMPFS}"
    ports          :
      - "${CORE_DB_PORT}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "--password=${CORE_DB_ROOT_PASSWORD}"]
      timeout: 20s
      retries: 10

  #############################################################################
  # PHPMyAdmin
  dbgui :
    image          : phpmyadmin/phpmyadmin
    container_name : aca_dev_phpmyadmin
    mem_limit      : 256m
    environment    :
      - "MYSQL_USERNAME=${CORE_DB_USER}"
      - "MYSQL_ROOT_PASSWORD=${CORE_DB_ROOT_PASSWORD}"
    links          :
      - database:db
    ports          :
      - "${PHPMYADMIN_PORT}:80"
    volumes:
      - "./tmp/env/${NODE_ENV}/phpmyadmin/sessions:/sessions"
    depends_on:
      database:
        condition: service_healthy
