SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE `__CORE_DB_NAME__`.`galleries`;
LOAD DATA LOCAL INFILE '__PATH__/galleries.csv'
INTO TABLE `__CORE_DB_NAME__`.`galleries`
CHARACTER SET UTF8
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

TRUNCATE TABLE `__CORE_DB_NAME__`.`renders`;
LOAD DATA LOCAL INFILE '__PATH__/renders.csv'
INTO TABLE `__CORE_DB_NAME__`.`renders`
CHARACTER SET UTF8
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

SET FOREIGN_KEY_CHECKS = 1;
